### ISSUE TITLE
Basic example not working.

### ISSUE THREAD

**Issue by jeetu7** [christianheine/prosemirror-svelte#3]
I am not able to get basic example working. I am not able to find any other better place to ask this question.
I installed prosemirror-svelte using 
  npm install --save prosemirror-svelte

(I even tried insataling dependencies with npm install --save  prosemirror-commands prosemirror-dropcursor prosemirror-gapcursor prosemirror-history prosemirror-inputrules prosemirror-keymap prosemirror-model prosemirror-schema-list prosemirror-state prosemirror-view prosemirror-schema-basic prosemirror-svelte)

Then I tried with the example "Essential usage" on the Readme.md. But I am not able to get the editor working. It is giving following error:
```
src/routes/test.svelte changed. rebuilding...
• server
'default' is imported from external module 'prosemirror-svelte' but never used
✗ client
Package subpath './package.json' is not defined by "exports" in /home/jeetu/work/arnav/webui/node_modules/w3c-keyname/package.json
/home/jeetu/work/arnav/webui/node_modules/prosemirror-svelte/ProsemirrorEditor.svelte:1
<script>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jeetu/work/arnav/webui/__sapper__/dev/server/server.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
> Server crashed
✔ service worker (206ms)
```

**Comment by trevyn** [comment]
`prosemirror-svelte` from npm is working fine for me on a Snowpack Svelte install. Possibly a bundler issue that you're running into?
